version: 2
jobs:
  build:
    working_directory: ~/exomiser
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: chmod +x mvnw
      - restore_cache:
          key: exomiser-{{ checksum "pom.xml" }}
      - run: ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - save_cache:
          paths:
            - ~/.m2
          key: exomiser-{{ checksum "pom.xml" }}
      - run: ./mvnw test -B
      - run: ./mvnw sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      #Save junit xml
      - run: mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/ \;
      #Save jars
      - run: mkdir -p $CIRCLE_ARTIFACTS/
      - run: find . -type f -regex ".*/target/exomiser.*jar" -exec cp {} $CIRCLE_ARTIFACTS/ \;
      - run: find . -type f -regex ".*/target/exomiser.*zip" -exec cp {} $CIRCLE_ARTIFACTS/ \;
      # Save test results
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
      - run: bash <(curl -s https://codecov.io/bash)